# Generated by Django 2.2.10 on 2020-07-28 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('dep_description', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('family_size', models.IntegerField()),
            ],
            options={
                'db_table': 'Family',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('place_of_birth', models.CharField(default='', max_length=100)),
                ('Home_town', models.CharField(default='', max_length=100)),
                ('residence', models.CharField(default='', max_length=100)),
                ('marital_status', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='MemberFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Family')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Member')),
            ],
            options={
                'db_table': 'member_family',
            },
        ),
        migrations.CreateModel(
            name='MemberDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Member')),
            ],
            options={
                'db_table': 'member_department',
            },
        ),
    ]
