# Generated by Django 2.2.10 on 2020-07-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(default='Ghana', max_length=20),
        ),
    ]
