# Generated by Django 2.2.10 on 2020-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_auto_20200728_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
    ]
