# Generated by Django 2.2.10 on 2020-11-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_auto_20200728_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='member',
            name='Spouse_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='baptism',
            field=models.CharField(default='Yes', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='baptism_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='baptism_place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_join',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='digital_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='fathers_location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='fathers_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='house_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='mothers_location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='mothers_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='name_of_childresn',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='member',
            name='number_of_children',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='other_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(default='Single', max_length=10),
        ),
    ]
