# Generated by Django 2.2.10 on 2021-02-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_auto_20210213_0044'),
        ('church', '0008_auto_20210213_0012'),
    ]

    operations = [
    ]
