# Generated by Django 2.2.10 on 2021-02-14 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_merge_20210213_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
