# Generated by Django 2.2.10 on 2021-02-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_auto_20210214_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='landmark',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
