# Generated by Django 2.2.10 on 2021-02-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_member_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontainer',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Member'),
        ),
    ]
